RoommatesExpensesManager/Controllers/RoommateController.cs
using RoommatesExpensesManager.Dal;
using RoommatesExpensesManager.Models;
using RoommatesExpensesManager.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace RoommatesExpensesManager.Controllers
{
    public class RoommateController : Controller
    {
        private bool Authorize()
        {
            //check if the user logged in
            if (Session["CurrentUser"] == null)
                return false;
            else
                return true;
        }

        public ActionResult ShowRoommatePage()
        {
            //show the home page of roommates
            if(!Authorize())
                return RedirectToAction("RedirectByUser", "Home");
            //remove gid from the session (added at showExpenses action)
            Session.Remove("gid");
            //get the groups of the user from DB
            User u = (User)(Session["CurrentUser"]);
            GroupRoommateDal gdal = new GroupRoommateDal();
            List<int> gids = (from g in gdal.GroupsRoommates
                              where g.userName == u.UserName
                              select g.groupID).ToList<int>();
            GroupDal groupd = new GroupDal();
            List<Group> MyGroups = (from g in groupd.Groups
                                    where gids.Contains(g.gid)
                                    select g).ToList<Group>();
            VMGroups grp = new VMGroups() { Groups = MyGroups };
            return View(grp);
        }

        public ActionResult ShowExpenses(int gid)
        {
            //show the expenses of the choosen group (asynchronous page)
            if (!Authorize())
                return RedirectToAction("RedirectByUser", "Home");
            Expense exp = new Expense();
            Session["gid"] = gid;
            return View(exp);
        }

        public ActionResult GetExpensesByJson()
        {
            //get json of all the expenses of the group
            if (!Authorize())
                return RedirectToAction("RedirectByUser", "Home");
            int gid = (int)Session["gid"];
            ExpenseDal expDal = new ExpenseDal();
            List<Expense> expenseGroup = (from e in expDal.Expenses
                                          where e.groupID == gid
                                          select e).ToList<Expense>();
            Thread.Sleep(2000);
            return Json(expenseGroup, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveNewExpense()
        {
            //save new expense in DB and return json of all expenses
            if (!Authorize())
                return RedirectToAction("RedirectByUser", "Home");
            ExpenseDal expDal = new ExpenseDal();
            Expense newExpense = new Expense();
            try
            {
                newExpense.UserName = ((User)(Session["CurrentUser"])).UserName;
                newExpense.Amount = Convert.ToDouble(Request.Form["Amount"]);
                newExpense.Store = Request.Form["Store"];
                newExpense.Category = Request.Form["categoryCombo"];
                newExpense.referenceNum = Request.Form["referenceNum"];
                newExpense.Comment = Request.Form["Comment"];
                newExpense.expDate = Convert.ToDateTime(Request.Form["expDate"]);
                newExpense.EntryDate = DateTime.Now;
                newExpense.groupID = ((Int32)(Session["gid"]));
            }
            catch (Exception)
            {
                ViewBag.addNewCExpenseError = "שדות חובה!";
            }
            ModelState.Clear();
            TryValidateModel(newExpense);
            if (ModelState.IsValid)
            {
                //save the new expense
                try
                {
                    expDal.Expenses.Add(newExpense);
                    expDal.SaveChanges();
                }
                catch (DbUpdateException)
                {
                    ViewBag.addNewCExpenseError = "התרחשה שגיאה בהוספת ההוצאה!";
                }
            }
            int gid = (int)Session["gid"];
            List<Expense> expenseGroup = (from e in expDal.Expenses
                                          where e.groupID == gid
                                          select e).ToList<Expense>();
            Thread.Sleep(2000);
            return Json(expenseGroup, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCategoriesByJson()
        {
            //get categories json (from manager controller)
            if (!Authorize())
                return RedirectToAction("RedirectByUser", "Home");
            return RedirectToAction("GetCategoriesByJson", "Manager");
        }
    }
}

RoommatesExpensesManager/Views/Roommate/ShowExpenses.cshtml
@model RoommatesExpensesManager.Models.Expense

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

<style>
    .tbl {
        background-color: #FFFFFF;
    }

    .headerTbl {
        background-color: #dcdcdc;
    }
</style>

@{
    ViewBag.Title = "הצגת הוצאות";
}

<h2>הוספת הוצאה חדשה</h2>

<form id="addExpenseForm" method="post" action="AddExpenseSubmit" class="form-group">
    <table class="table" id="tableForm">
        <tr>
            <td>
                <label>תאריך תשלום</label>
                <input type="date" id="expDate" name="expDate" class="form-control">
            </td>
            <td>
                <label>קטגוריה</label>
                <select id="categoryDD" name="categoryCombo" class="form-control"></select>
                <div style="color:red" id="loadStatuss"></div>
            </td>
            <td>
                <label>מקום הקנייה</label>
                @Html.TextBoxFor(m => m.Store, new { Class = "form-control" })
                <div style="color:red">@Html.ValidationMessageFor(x => x.Store)</div>
            </td>
            <td>
                <label>סכום</label>
                @Html.TextBoxFor(m => m.Amount, new { Class = "form-control" })
                <div style="color:red">@Html.ValidationMessageFor(x => x.Amount)</div>
            </td>
            <td>
                <label>מספר אסמכתא</label>
                @Html.TextBoxFor(m => m.referenceNum, new { Class = "form-control" })
                <div style="color:red">@Html.ValidationMessageFor(x => x.referenceNum)</div>
            </td>
            <td>
                <label>הערות</label>
                @Html.TextBoxFor(m => m.Comment, new { Class = "form-control" })
                <div style="color:red">@Html.ValidationMessageFor(x => x.Comment)</div>
            </td>
        </tr>
    </table>
    <br />
    <input class="btn btn-primary" id="addExspense" type="button" onclick="SendNewExpenese()" value="הוספה" />
    <input class="btn btn-primary" id="addExspense" type="button" onclick="location.href='@Url.Action( "ShowRoommatePage","Roommate")'" value="סיום" />
</form>

<div style="color:red">@ViewBag.addNewCExpenseError</div>

<script>
    var categoryDropDown = $('#categoryDD');
    categoryDropDown.empty();
    categoryDropDown.append('<option selected="true" disabled>בחר קטגוריה</option>');
    $("#loadStatuss").text("טוען קטגוריות... אנא המתן");
    $.getJSON("GetCategoriesByJson", function (categories) {
        for (i = 0; i < categories.length; i++) {
            categoryDropDown.append($('<option></option>').attr('value', categories[i].Type).text(categories[i].Type));
        }
    $("#loadStatuss").text("");
    });
</script>

<h2>הוצאות הקבוצה</h2>
<div style="color:red" id="loadStatus"></div>
<table id="showExpensesTbl" class="table table-bordered table-responsive table-hover tbl">
    <tr class="headerTbl">
        <td>תאריך הוספה </td>
        <td>תאריך תשלום </td>
        <td>שם שותף </td>
        <td>קטגוריה </td>
        <td>חנות </td>
        <td>סכום </td>
        <td>אסמכתא</td>
        <td>הערות </td>
    </tr>
</table>

<script>
    $("#loadStatus").text("טוען הוצאות... אנא המתן");
    $.post("GetExpensesByJson", null, BindDataToTable);

    function BindDataToTable(expenseGroup) {
        $("#showExpensesTbl").find("tr:gt(0)").remove();
    var exspenseTable = $("#showExpensesTbl");
        for (i = 0; i < expenseGroup.length; i++) {
            var entryDate = new Date(parseInt(expenseGroup[i].EntryDate.substr(6)));
            var expDate = new Date(parseInt(expenseGroup[i].expDate.substr(6)));
            var entryDateStr = entryDate.getDate() + '/' +
                (entryDate.getMonth() + 1) + '/' +
                entryDate.getFullYear() + ' ' +
                entryDate.toLocaleTimeString();
            var expDateStr = expDate.getDate() + '/' +
                (expDate.getMonth() + 1) + '/' +
                expDate.getFullYear();
            var newRow = "<tr>" +
                "<td>" + entryDateStr + "</td>" +
                "<td>" + expDateStr + "</td>" +
                "<td>" + expenseGroup[i].UserName + "</td>" +
                "<td>" + expenseGroup[i].Category + "</td>" +
                "<td>" + expenseGroup[i].Store + "</td>" +
                "<td>" + expenseGroup[i].Amount + "</td>" +
                "<td>" + expenseGroup[i].referenceNum + "</td>" +
                "<td>" + expenseGroup[i].Comment + "</td>" +
                "</tr>";
        exspenseTable.append(newRow);
    }
    $("#loadStatus").text("");
}

function SendNewExpenese() {
    var expenseFormData = $("#addExpenseForm").serialize();
    $("#loadStatus").text("שומר הוצאה... אנא המתן");
    $.post("SaveNewExpense", expenseFormData, BindDataToTable);
    $("#Amount").val("");
    $("#Store").val("");
    $("#categoryDD").val('בחר קטגוריה');
    $("#referenceNum").val("");
    $("#expDate").val("");
    $("#Comment").val("");
}
</script>

RoommatesExpensesManager/Views/Roommate/ShowGroups.cshtml
@model RoommatesExpensesManager.ViewModel.VMGroups
@using RoommatesExpensesManager.Models;

<style>
    .tbl {
        background-color: #FFFFFF;
    }

    .headerTbl {
        background-color: #dcdcdc;
    }

    .selectBtn {
        color: #FF0000;
    }
</style>

@using (Html.BeginForm("ShowExpense", "Roommate", FormMethod.Post))
{
    <span style="font-size:xx-large"><b> הקבוצות שלי </b></span>
    <br />
    <br />
    <table class="table table-bordered table-responsive table-hover tbl">
        <tr class="headerTbl">
            <td>  מזהה קבוצה  </td>
            <td>מנהל </td>
            <td>עיר </td>
            <td>רחוב </td>
            <td>מספר </td>

        </tr>
        @foreach (Group obj in Model.Groups)
        {
            <tr>
                <td>@obj.gid </td>
                <td>@obj.managerUserName </td>
                <td>@obj.city </td>
                <td>@obj.street </td>
                <td>@obj.aptNum </td>
                <td>@Html.ActionLink("צפיה בהוצאות הקבוצה", "ShowExpenses", "Roommate", new { gid = @obj.gid }, new { Class = "selectBtn" })</td>
            </tr>
        }
    </table>

}

RoommatesExpensesManager/Views/Roommate/ShowRoommatePage.cshtml
@model RoommatesExpensesManager.ViewModel.VMGroups
@using RoommatesExpensesManager.Models

@{
    ViewBag.Title = "ההוצאות שלי";
}

<br/>

@Html.Partial("ShowGroups", Model)